# Generated by Django 3.1.14 on 2023-08-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20230809_1606'),
        ('pokemon_entities', '0004_auto_20230810_1436'),
    ]

    operations = [
    ]
